# Label configuration for PR auto-labeling

'documentation':
  - changed-files:
    - any-glob-to-any-file: ['**/*.md', 'docs/**']

'dependencies':
  - changed-files:
    - any-glob-to-any-file: ['package.json', 'bun.lock', 'package-lock.json']

'ci/cd':
  - changed-files:
    - any-glob-to-any-file: ['.github/**']

'frontend':
  - changed-files:
    - any-glob-to-any-file: ['src/**/*.tsx', 'src/**/*.ts', 'src/**/*.css']

'components':
  - changed-files:
    - any-glob-to-any-file: ['src/components/**']

'ui':
  - changed-files:
    - any-glob-to-any-file: ['src/components/ui/**']

'laundry':
  - changed-files:
    - any-glob-to-any-file: ['src/components/laundry/**']

'api':
  - changed-files:
    - any-glob-to-any-file: ['api/**']

'config':
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.config.js'
      - '**/*.config.ts'
      - 'tsconfig*.json'
      - '.eslintrc*'
      - '.prettierrc*'

'pwa':
  - changed-files:
    - any-glob-to-any-file:
      - 'manifest.json'
      - 'public/service-worker.js'
      - 'public/icons/**'

'styles':
  - changed-files:
    - any-glob-to-any-file: ['**/*.css', 'tailwind.config.js']

